services:
  palacms:
    # Use prebuilt image from GitHub Container Registry
    image: ghcr.io/palacms/palacms:latest
    
    # Alternatively, build from local Dockerfile
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    
    container_name: palacms
    
    # Restart policy
    restart: unless-stopped
    
    # Port mapping
    ports:
      - "8080:8080"
    
    # Environment variables
    environment:
      # Core PalaCMS configuration
      - PALA_SUPERUSER_EMAIL=${PALA_SUPERUSER_EMAIL:-}
      - PALA_SUPERUSER_PASSWORD=${PALA_SUPERUSER_PASSWORD:-}
      - PALA_USER_EMAIL=${PALA_USER_EMAIL:-}
      - PALA_USER_PASSWORD=${PALA_USER_PASSWORD:-}
      - PALA_VERSION=${PALA_VERSION:-3.0.0-beta.1}
      
      # Database configuration
      - DATABASE_TYPE=${DATABASE_TYPE:-sqlite}
      - DATABASE_URL=${DATABASE_URL:-}
      
      # AWS S3 Storage
      - AWS_S3_ENABLED=${AWS_S3_ENABLED:-false}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET:-}
      - AWS_S3_REGION=${AWS_S3_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_S3_ENDPOINT=${AWS_S3_ENDPOINT:-}
      - AWS_S3_PUBLIC_URL=${AWS_S3_PUBLIC_URL:-}
      
      # AWS SES Email
      - AWS_SES_ENABLED=${AWS_SES_ENABLED:-false}
      - AWS_SES_REGION=${AWS_SES_REGION:-us-east-1}
      - AWS_SES_FROM_ADDRESS=${AWS_SES_FROM_ADDRESS:-}
      - AWS_SES_ACCESS_KEY_ID=${AWS_SES_ACCESS_KEY_ID:-}
      - AWS_SES_SECRET_ACCESS_KEY=${AWS_SES_SECRET_ACCESS_KEY:-}
      
      # AWS CloudFront CDN
      - AWS_CLOUDFRONT_ENABLED=${AWS_CLOUDFRONT_ENABLED:-false}
      - AWS_CLOUDFRONT_DISTRIBUTION_ID=${AWS_CLOUDFRONT_DISTRIBUTION_ID:-}
      - AWS_CLOUDFRONT_DOMAIN=${AWS_CLOUDFRONT_DOMAIN:-}
      
      # AWS Cognito Authentication
      - AWS_COGNITO_ENABLED=${AWS_COGNITO_ENABLED:-false}
      - AWS_COGNITO_USER_POOL_ID=${AWS_COGNITO_USER_POOL_ID:-}
      - AWS_COGNITO_CLIENT_ID=${AWS_COGNITO_CLIENT_ID:-}
      - AWS_COGNITO_CLIENT_SECRET=${AWS_COGNITO_CLIENT_SECRET:-}
      - AWS_COGNITO_REGION=${AWS_COGNITO_REGION:-us-east-1}
      - AWS_COGNITO_ACCESS_KEY_ID=${AWS_COGNITO_ACCESS_KEY_ID:-}
      - AWS_COGNITO_SECRET_ACCESS_KEY=${AWS_COGNITO_SECRET_ACCESS_KEY:-}
    
    # Volume for persistent data storage
    volumes:
      - palacms-data:/app/pb_data
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits (optional, adjust based on your needs)
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 1G
    #     reservations:
    #       cpus: '0.5'
    #       memory: 512M

volumes:
  # Named volume for PalaCMS data persistence
  palacms-data:
    driver: local

# Optional: Add a network if you need to connect to other services
# networks:
#   palacms-network:
#     driver: bridge
